name: Deploy (Development)

on:
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

env:
  ARM_USE_OIDC: false

jobs:
  dev:
    environment: dev
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # This is required for requesting the OIDC JWT Token
      contents: read # Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # TODO: add dotnet test step

      - name: Build and Deploy
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./src/Plurish.Game.Api/Dockerfile
          registryUrl: devplurish.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: dev-capp-api-game
          resourceGroup: dev-rg-plurish
          imageToBuild: devplurish.azurecr.io/api/game:${{ github.sha }}
          targetPort: 8080
          _buildArgumentsKey_: |
            _buildArgumentsValues_
    
  # TODO: add hml stage